### PR TITLE
Added Mandatory = $true in few places were it was just Mandatory

### PR DESCRIPTION
**Pull request by kvprasoon**
Backward compatibility for version 2

### CODE REVIEW

**Comment by DexterPOSH** [comment]
@kvprasoon working on a better ops validation DSL at the moment (private at the moment).
Let me know, if you want to see it and give some feedback.

Remotely does not fulfill our needs for the Ops validation, so not working on it for now.

**Comment by kvprasoon** [comment]
@DexterPOSH  "PSRemotely" is it the same ?
I would like to see it...

**Comment by DexterPOSH** [comment]
Yes @kvprasoon , Hopefully I will make it public today. Setting up Appveyor and GitHub pages now .
Added you to the private repo, take a look at the 'develop' branch.

**Comment by jpuskar** [comment]
@DexterPOSH, are you still working on this? I'm interested as well.

**Comment by DexterPOSH** [comment]
@jpuskar  Yeah, I made my repo public
https://github.com/DexterPOSH/PSRemotely

Also watch out for an article on PowerShell magazine today 😄

**Comment by DexterPOSH** [comment]
@jpuskar Circling back to add the link to my article.
http://www.powershellmagazine.com/2017/04/07/psremotely-framework-to-enable-remote-operations-validation/

**Pull request closed without merging**
